collections:
  authors:
    output: true
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme